version: '3'
services:
  frontend:
    image: albh/converter-app:application
    volumes:
      - ./Application/app:/app
    ports:
      - "5000:5000"
    networks:
      - converter_net

  converter-service:
    image: albh/converter-app:converter_service
    volumes:
      - ./Converter_Service/app:/app
    networks:
      - converter_net
networks:
  converter_net:
